defaultBaseImage: cgr.dev/chainguard/glibc-dynamic@sha256:05353305142a1ae7c1e27d2cdd09df1650874db3e4c004b3cb2f6dd794e7320f
defaultEnv:
- CGO_ENABLED=1
- GOOS=linux
builds:
- id: native-probe
  dir: .
  main: ./cmd/native-probe
