minimum_pre_commit_version: "3.2.0"
default_install_hook_types:
  - pre-commit
default_stages:
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.13.2
    hooks:
      - id: golangci-lint-config-verify
      - id: golangci-lint-full
